name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        nim: [1.2.6, stable]
    steps:
    - uses: actions/checkout@v2
    - uses: iffy/install-nim@v3
      with:
        version: ${{ matrix.nim }}
    - name: Build
      run: nimble install -y
    - name: Test
      run: nimble test -y
